---
title: "HDD profile; date `r Sys.Date()`; generated by `r Sys.info()['effective_user']`"
params:
  path_block: ""
---

```{r echo=FALSE}
if (!fs::is_absolute_path(params$path_block))
  rlang::abort(stringr::str_c(
    "A block device path must be specified ",
    "in the rmarkdown::render params argument."))
```

```{r, functions, echo=FALSE,warning=FALSE,message=FALSE}
library(tidyverse)
library(fs)

#' @param path_block Path to the raw device, e.g. /dev/sda
#' @return lsblk stdout as character vector
lsblk_device <- function(path_block) {
  system2(
    command="lsblk", stdout=TRUE,
    args=c(
      "-f", "-o", "SERIAL,NAME,MAJ:MIN,SIZE,FSTYPE,LABEL,UUID",
      path_block))}

#' @param path_block Path to the raw device, e.g. /dev/sda
#' @return Character vector of partition(s) of the raw device.
get_partitions <- function(path_block) {
  lsblk_output <- system2(
    command="lsblk", stdout=TRUE,
    args=c("--list", "--noheadings", "--paths", "-o", "NAME", path_block))
  parts <- discard(lsblk_output, ~.x == path_block)
  if (length(parts) == 0)
    rlang::abort(str_glue("{path_block} has no partitions.")) 
  parts}

#' @param path_part Path to the partition, e.g. /dev/sda1
#' @details Uses udisksctl, which should not require superuser privilleges.
#' @return Path to directory where this partition was mounted.
mount_partition <- function(path_part) {
  udisksctl_output <- system2(
    command="udisksctl", stdout=TRUE,
    args=c("mount", "--no-user-interaction", "--block-device", path_part))
  mounted_at <- udisksctl_output %>%
    str_remove(str_glue("Mounted {path_part} at "))
  if (!is_absolute_path(mounted_at))
    abort(str_glue("Something went wrong mounting {path_part}."))
  mounted_at}

#' @param path_part Path to the partition, e.g. /dev/sda1
#' @return TRUE
unmount_partition <- function(path_part) {
  udisksctl_output <- system2(
    command="udisksctl", stdout=TRUE,
    args=c("unmount", "--no-user-interaction", "--block-device", path_part))
  if (!udisksctl_output == str_glue("Unmounted {path_part}."))
    abort("Something went wrong unmounting {path_part}.")
  TRUE}

#' @param path_directory Path to a directory, e.g. /media/ning/6194-A59E
#' @return tree stdout as character vector
tree_directory <- function(path_directory) {
  system2("tree", c("-c", "--timefmt", "%Y-%m-%d", path_directory), stdout=TRUE)}
```

### Block devices

```{r, comment=NA}
lsblk_device(params$path_block) %>% str_flatten("\n") %>% cat()
```

### Contents

```{r, comment=NA}
for (partition in get_partitions(params$path_block)) {
  message(str_glue("=v= {partition} =v="))
  mounted <- mount_partition(partition)
  system2("df", c("-h", mounted), stdout=TRUE) %>% str_flatten("\n") %>% cat()
  cat("\n\n"); tree_directory(mounted) %>% str_flatten("\n") %>% cat()
  invisible(unmount_partition(partition))} 
```

### Function definitions

```{r, ref.label="functions", eval=FALSE}
```
